spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
#    url: jdbc:mysql://fitnessu-db.cqgux8nf2jkp.ap-northeast-2.rds.amazonaws.com:3306/fitnessu?serverTimezone=Asia/Seoul
    url: jdbc:mysql://localhost:3306/fitnessu?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    #password: 0116
    password: tjrwlswntkdwnsrb1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
      #ddl-auto: update
    properties:
      hibernate:
        #      show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


server:
  address: localhost
  port: 8080

